# Setup
title: Laanaya | Knowledge base
url: https://info.laanaya.org
description: "Take your mind off the technicalities, leave it to us. It is our goal to work with you to guarantee that your server will run smoothly. We will be the first to respond if there are any issues with your server, so you can sleep well tonight."
paginate: 1
baseurl: ""
permalink: pretty

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
sass:
  sass_dir: _sass
  style: ':compressed'
author:
  name: Amin Laanaya
  url: 'https://laanaya.org'
  email: amin@laanaya.org
version: 3.0.0
nav:
  - title: Knowledge base
    url: https://info.laanaya.org/archive
  - title: Home
    url: https://laanaya.org/
